
days_in_month = {
    1: 31,
    2: 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31
}
landmask_ref = {
    66896: 'slm',
    67420: 'wlm'
}
abbrev_dict = {
    'All-Hist': 'hist',
    'Plus15-Future': 'p15',
    'Plus20-Future': 'p20',
    'plus15_change': 'p15_rel',
    'plus20_change': 'p20_rel',
    'NorESM1': 'n',
    'MIROC5': 'm',
    'ECHAM-6-3-LR': 'e',
    'CAM4-2degree': 'c'
}

var_dict = {
    'G_RIVER_AVAIL_': {'var_name': 'dis',
                       'mass_unit': None,
                       'area_unit': None},
    'G_RIVER_AVAIL': {'var_name': 'dis',
                      'mass_unit': None,
                      'area_unit': None},
    'G_RIVER_IN_UPSTREAM_': {'var_name': 'dis_upstream',
                             'mass_unit': None,
                             'area_unit': None},
    'G_PRECIPITATION_': {'var_name': 'pr',
                         'mass_unit': 'kg',
                         'area_unit': 'm2'},
    'G_CONSISTENT_PRECIPITATION_km3_': {'var_name': 'precip',
                                        'mass_unit': None,
                                        'area_unit': None},
    'G_FLOWDIR': {'var_name': 'flowdir',
                  'mass_unit': None,
                  'area_unit': None},
    'G_BASINS': {'var_name': 'basins',
                 'mass_unit': None,
                 'area_unit': None},
    'G_BASINS_2': {'var_name': 'basins2',
                   'mass_unit': None,
                   'area_unit': None},
    'GPREC': {'var_name': 'precip',
              'mass_unit': None,
              'area_unit': None},
    'G_TEMPERATURE_': {'var_name': 'temperature',
                       'mass_unit': None,
                       'area_unit': None},
    'GTEMP': {'var_name': 'temperature',
              'mass_unit': None,
              'area_unit': None},
    'G_SOIL_WATER_': {'var_name': 'rootmoist',
                      'mass_unit': None,
                      'area_unit': None},
    'G_SNOW_WATER_EQUIV_': {'var_name': 'swe',
                            'mass_unit': None,
                            'area_unit': None},
    'G_SNOW_FALL_': {'var_name': 'psnow',
                     'mass_unit': None,
                     'area_unit': None},
    'G_CELL_RUNOFF_mm_': {'var_name': 'net_cell_runoff',
                          'mass_unit': 'mm',
                          'area_unit': 'm2'},
    'G_CELL_RUNOFF_': {'var_name': 'net_cell_runoff',
                       'mass_unit': None,
                       'area_unit': None},
    'G_NETUSE_GW_m3_': {'var_name': 'na_g',
                        'mass_unit': None,
                        'area_unit': None},
    'G_NETUSE_SW_m3_': {'var_name': 'na_s',
                        'mass_unit': None,
                        'area_unit': None},
    'G_ACTUAL_WATER_CONSUMPTION_': {'var_name': 'actual_water_use',
                                    'mass_unit': None,
                                    'area_unit': None},
    'G_INFLC.9': {'var_name': 'infl_arcid',
                  'mass_unit': None,
                  'area_unit': None},
    'G_ACTUAL_NAS_': {'var_name': 'actual_use_sw',
                         'mass_unit': None,
                         'area_unit': None},
    'G_ACTUAL_NAG_': {'var_name': 'actual_use_gw',
                         'mass_unit': None,
                         'area_unit': None},
    'G_CELL_AET_': {'var_name': 'cell_aet',
                    'mass_unit': 'mm',
                    'area_unit': 'm2'},
    'G_CELLAET_CONSUSE_km3_': {'var_name': 'cell_aet_consuse',
                               'mass_unit': 'km3',
                               'area_unit': 'contarea'},
    'G_TOTAL_PET_': {'var_name': 'total_pet',
                     'mass_unit': None,
                     'area_unit': None},
    'G_TOTAL_STORAGES_STARTEND_km3_': {'var_name': 'tws_startend',
                                       'mass_unit': None,
                                       'area_unit': None},
    'G_SATIS_USE_': {'var_name': 'statisfied_use',
                     'mass_unit': None,
                     'area_unit': None},
    'G_IRRIG_WITHDRAWAL_USE_HISTAREA_m3_': {'var_name': 'irrig_withdrawal_use',
                                            'mass_unit': None,
                                            'area_unit': None},
    'G_IRRIG_CONS_USE_HISTAREA_m3_': {'var_name': 'irrig_cons_use',
                                      'mass_unit': None,
                                      'area_unit': None},
    'G_FRACTRETURNGW_IRRIG': {'var_name': 'frig',
                              'mass_unit': None,
                              'area_unit': None},
    'G_UNSAT_USE_': {'var_name': 'unsat_use',
                     'mass_unit': None,
                     'area_unit': None},
    'G_GLO_WETL_EXTENT_km2_': {'var_name': 'glo_wetl_extent',
                               'mass_unit': None,
                               'area_unit': None},
    'G_TOTAL_GW_RECHARGE_km3_': {'var_name': 'total_gw_recharge',
                                 'mass_unit': None,
                                 'area_unit': None},
    'G_ALLOC_USE_': {'var_name': 'allocated_use',
                     'mass_unit': None,
                     'area_unit': None},
    'G_SATIS_ALLOC_USE_IN_2NDCELL_': {'var_name': 'alloc_use_in2ndcell',
                                      'mass_unit': None,
                                      'area_unit': None},
    'G_CONT_AREA_OUT_km2': {'var_name': 'contarea',
                            'mass_unit': None,
                            'area_unit': None},
    'G_TOTAL_GW_RECHARGE_mm_': {'var_name': 'total_gw_recharge',
                                'mass_unit': None,
                                'area_unit': None},
    'G_GW_RECHARGE_km3_': {'var_name': 'qr',
                           'mass_unit': 'km3',
                           'area_unit': None},
    'G_GW_RECHARGE_mm_': {'var_name': 'qr',
                          'mass_unit': 'mm',
                          'area_unit': 'm2'},
    'G_GWR_SURFACE_WATER_BODIES_km3_': {'var_name': 'qr',
                                        'mass_unit': 'km3',
                                        'area_unit': 'contarea'},
    'G_TOTAL_STORAGES_mm_': {'var_name': 'tws',
                             'mass_unit': 'mm',
                             'area_unit': 'm2'},
    'G_TOTAL_CONS_USE_GW_HISTAREA_m3_': {'var_name': 'cons_use_gw',
                                         'mass_unit': None,
                                         'area_unit': None},
    'G_TOTAL_WITHDRAWAL_USE_GW_HISTAREA_m3_': {'var_name': 'withdrawal_gw',
                                               'mass_unit': None,
                                               'area_unit': None},
    'G_LAND_AREA_FRACTIONS_': {'var_name': 'landareafr',
                               'mass_unit': None,
                               'area_unit': None},
    'G_GROUND_WATER_STORAGE_mm_': {'var_name': 'gws',
                                   'mass_unit': 'mm',
                                   'area_unit': 'm2'},
    'G_SOIL_WATER_STORAGE_mm_': {'var_name': 'sws',
                                 'mass_unit': 'mm',
                                 'area_unit': 'm2'},
    'G_GLOWET': {'var_name': 'glwd_glowet',
                             'mass_unit': None,
                             'area_unit': None},
    'G_LOCWET': {'var_name': 'glwd_locwet',
                 'mass_unit': None,
                 'area_unit': None}
}

output_options_no = {
    0: 'G_PRECIPITATION_[YEAR].12.UNF0',
    1: 'G_AET_[YEAR].12.UNF0',
    2: 'G_CELL_AET_[YEAR].12.UNF0/G_LAND_AET_[YEAR].12.UNF0',
    26: 'G_TOTAL_PET_[YEAR].12.UNF0',
    27: 'G_RIVER_AVAIL_[YEAR].12.UNF0',
    28: 'G_RIVER_IN_UPSTREAM_[YEAR].12.UNF0',
    44: 'G_ACTUAL_NAS_[YEAR].12.UNF0',
    46: 'G_ACTUAL_WATER_CONSUMPTION_[YEAR].12.UNF0',
    58: 'G_CELLAET_CONSUSE_km3_[YEAR].12.UNF0',
    94: 'G_TOTAL_STORAGE_km3_[YEAR]*.UNF0',
    96: 'G_TOTAL_STORAGE_STARTEND_km3_[YEAR].2.UNF0'
}
output_options_dict = {
    'precip_mon': 0,
    'aet_mon': 1,
    'cell_aet_mon': 2,
    'total_pet_mon': 26,
    'dis_mon': 27,
    'upstream_dis_mon': 28,
    'actual_use_sw_mon': 44,
    'total_water_cons_mon': 46,
    'cell_aet_consuse_mon': 58,
    'tws_daily': 94,
    'tws_daily_startend': 96,

}

